# Generated by Django 5.0.4 on 2025-02-20 17:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False, editable=False)),
                ("data", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "db_table": "posts",
            },
        ),
    ]
