services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: unicon-blog
    ports:
      - 5441:5432
    networks:
      - "local-development"
  app:
    build:
      dockerfile: deployment/Dockerfile.deploy
    environment:
      - ENVIRONMENT=docker
    env_file:
      - ./.envs/.env.docker
    ports:
      - 9001:9000
    networks:
      - "local-development"
networks:
  local-development:
